name: Build and Deploy SKS Website to UpYun

on:
  push:
    branches:
      - master  # 如果你的主分支是 master，请改为 master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 拉取仓库代码
    - name: Checkout shorthand
      uses: actions/checkout@v4

    # 2. 设置 Node.js 环境
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # 3. 运行重构脚本（自动下载 yaml 并生成 out/）
    - name: Generate Website
      run: node scripts/generate-site.js

    # 4. 运行发布脚本（自动下载 upyun 并将 out/ 上传到云空间）
    - name: Deploy to UpYun
      env:
        YP_SPACE: ${{ vars.YP_SPACE }}
        YP_NAME: ${{ vars.YP_NAME }}
        YP_PWD: ${{ secrets.YP_PWD }}
      run: node scripts/youpai-sync.js
